name: Go Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Download dependencies
        run: go mod download

      - name: Run unit tests
        run: go test ./internal/... ./pkg/... -v

      - name: Build go-avro CLI binary
        run: go build -o go-avro ./main.go

      - name: Run CLI integration tests
        run: go test ./test -v
